### ISSUE TITLE
mockup and front-end

### ISSUE THREAD

**Issue by pinamiranda** [devisefutures/assina#2]
We need to have better UX/UI.
Phases:
1. mockup of the UI/UX
2. request Scytales to develop the javascript code (or HTML + CSS of the pages)
3. integrate in assina front-end (react)

**Comment by Rolando2000** [comment]
Link to the application where the mockups were made: https://wireframepro.mockflow.com/view/MKB5N3Gjiqb

![all_pages](https://github.com/devisefutures/assina/assets/61158161/6984b028-329b-4a63-984d-984fa6c1e4fd)
![certificates](https://github.com/devisefutures/assina/assets/61158161/89863bac-2f7a-476f-a205-63a0d09e0533)
![initial_page](https://github.com/devisefutures/assina/assets/61158161/da926d2d-58df-4ca4-a4b5-fcce06e1d0e6)
![Signing_step1](https://github.com/devisefutures/assina/assets/61158161/0c52f132-b2dc-4a94-974b-1e2c77d34b49)
![Signing_step2](https://github.com/devisefutures/assina/assets/61158161/8df0c408-1d4b-49bc-9df7-ea31578d0443)
![Signing_step3](https://github.com/devisefutures/assina/assets/61158161/6ee1e896-5608-4a7d-bb26-a883de3bee34)
![Signing_step4](https://github.com/devisefutures/assina/assets/61158161/da58eddd-3555-4ca8-a2c6-10384f39775b)
![view_profile](https://github.com/devisefutures/assina/assets/61158161/3bb55e8a-6d03-44c5-ac76-137258d05529)
