### ISSUE TITLE
Error when trying to sign a file without having a certificate

### ISSUE THREAD

**Issue by pinamiranda** [devisefutures/assina#23]
The interface should not allow to start signing a file, without having at least one certificate Meaning, the "Sign Document" button in the minehome page should be inactive until the user has issued one certificate.

**Comment by Rolando2000** [comment]
When attempting to proceed by clicking the 'Sign Document' button, the user is blocked and not allowed to proceed, and a notification is displayed in the top left corner informing them that they have no certificates ('no certificates').

![image](https://github.com/devisefutures/assina/assets/61158161/40570353-ebc0-43cb-a512-a5bb0b3a5c1c)


If the user attempts to directly access the route via the URL ("/sign"), a notification is displayed informing them that they have no certificates ('no certificates'), and after 3 seconds, they are redirected back to the profile page ('/profile').

![image](https://github.com/devisefutures/assina/assets/61158161/90a1ea36-7516-4af5-973f-e24e9b616064)
