### ISSUE TITLE
Add information that only PDF documents are signed

### ISSUE THREAD

**Issue by pinamiranda** [devisefutures/assina#25]
+ Change the button "Sign document" to "Sign PDF document"
+ Change the Header "Signing Documents" to "Signing PDF Document"
+ Change the option "Upload" to "Upload PDF"
+ Change the Option "Sign" to "Sign PDF"
+ Change the option "Download" to "Download signed PDF"

**Comment by Rolando2000** [comment]
Change successfully completed.
