### ISSUE TITLE
Integrate OID4VP

### ISSUE THREAD

**Issue by pinamiranda** [devisefutures/assina#3]
OID4VP will be used to:
+ authentication for login (if the user account does not exist, it will be created)
+ authorization to generate the key pair
+ consent in using the signing private key to sign a PDF document

OID4VP expected flow (using Babis web services and probably his Java library - not sure about the last one):
+ request PID
+ validate that the PID is valid
+ extract the attributes and metadata
+ integrate with the "assina" code

**Comment by MarianaFilipa** [comment]
The authorization to generate the key pair may not be required, as the user is already required to be authenticated for key pair creation and must authorize the usage of a key pair to sign a PDF document using OID4VP.
