### ISSUE TITLE
Log in as user X and sign in as user Y

### ISSUE THREAD

**Issue by pinamiranda** [devisefutures/assina#30]
Bug reported by Netcompany-Intrasoft/Scytales (NiScy):

+ I log in as User X to this link, create a certificate, and proceed to sign (in the 3rd step, it asks you to sign with the wallet -> it displays a QR code which I now scan as User Y).

+ In the wallet, the details requested by the verifier are displayed, I tap on 'share' -> a success message appears in the wallet, but the following error pops up in the signer.

<img width="861" alt="image" src="https://github.com/devisefutures/assina/assets/10962820/e4b3099d-7a56-4098-8004-6908c1644c33">

Note: the signature shall not be allowed, and a comprehensive error message must be shown to the user

**Comment by MarianaFilipa** [comment]
The backend code was updated to handle additional exceptions for this functionality and the message displayed to the user was also updated.
