### ISSUE TITLE
Add image of the EUDI Wallet to the QR code background

### ISSUE THREAD

**Issue by pinamiranda** [devisefutures/assina#40]
Low priority.
something like: 
<img width="205" alt="image" src="https://github.com/devisefutures/assina/assets/10962820/3281df92-a549-478e-acda-5cf2b5797fb7">

**Comment by MarianaFilipa** [comment]
Example of the updated QR code:
![Qrcode_example](https://github.com/devisefutures/assina/assets/62109899/5ad64e05-591d-41eb-987d-34e62d39ea5e)
